---
title: "ENVS 193DS Final"
author: "Kierra Miller"
date: "2026-06-07"
format:
  pdf:
    toc: true
---

GitHub Repository: <https://github.com/kierramiller/ENVS-193DS_spring-2026_final>




```{r}

# Set up: load packages and dataset 

library(tidyverse)
library(janitor)
library(readxl)
library(DHARMa)
library(AICcmodavg)
library(ggeffects)

nests <- read_csv("nest_data_final.csv")
```

# Problem 1. 

## a. Transparent statistical methods 

In part 1, my co-worker used a logistic regression to evaluate whether distance to the water's edge predicted the probability of American Avocet microhabitat use.In part 2, my co-worker used a chi-square test of independence to evaluate whether habitat use differed among bird species.

## b. Suggestions for rewriting 

## c. Further analysis 


# Problem 2. Data Analysis 

## a. Clean and wrangle 
## b. Response variable 
## c. Purpose of study 
## d. Table of models 
## e. Run the models 
## f. Select the best model 
## g. Check the diagnostics 
## h. Visualize the model predictions 
## i. Figure caption 
## j. Calculate model predictions 
## k. Interpret your results 


# Problem 3. Affective and exploratory visualizations 
##  a. Comparing visualizations 

## b. Designing an analysis 


## c. Check any assumptions and run your analysis 

## d. Create a visualization 

## e. Write a caption 
## f. Write about your results 
## g. Sharing your affective visualization 







